// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.1
// source: pics.proto

package protoc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Pics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pic []*Pics_Picture `protobuf:"bytes,1,rep,name=pic,proto3" json:"pic,omitempty"`
}

func (x *Pics) Reset() {
	*x = Pics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pics) ProtoMessage() {}

func (x *Pics) ProtoReflect() protoreflect.Message {
	mi := &file_pics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pics.ProtoReflect.Descriptor instead.
func (*Pics) Descriptor() ([]byte, []int) {
	return file_pics_proto_rawDescGZIP(), []int{0}
}

func (x *Pics) GetPic() []*Pics_Picture {
	if x != nil {
		return x.Pic
	}
	return nil
}

type Pics_Picture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	PicData  []byte `protobuf:"bytes,3,opt,name=pic_data,json=picData,proto3" json:"pic_data,omitempty"`
}

func (x *Pics_Picture) Reset() {
	*x = Pics_Picture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pics_Picture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pics_Picture) ProtoMessage() {}

func (x *Pics_Picture) ProtoReflect() protoreflect.Message {
	mi := &file_pics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pics_Picture.ProtoReflect.Descriptor instead.
func (*Pics_Picture) Descriptor() ([]byte, []int) {
	return file_pics_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Pics_Picture) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pics_Picture) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Pics_Picture) GetPicData() []byte {
	if x != nil {
		return x.PicData
	}
	return nil
}

var File_pics_proto protoreflect.FileDescriptor

var file_pics_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x22, 0x80, 0x01, 0x0a, 0x04, 0x50, 0x69, 0x63, 0x73, 0x12, 0x26, 0x0a,
	0x03, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2e, 0x50, 0x69, 0x63, 0x73, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x03, 0x70, 0x69, 0x63, 0x1a, 0x50, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x69, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pics_proto_rawDescOnce sync.Once
	file_pics_proto_rawDescData = file_pics_proto_rawDesc
)

func file_pics_proto_rawDescGZIP() []byte {
	file_pics_proto_rawDescOnce.Do(func() {
		file_pics_proto_rawDescData = protoimpl.X.CompressGZIP(file_pics_proto_rawDescData)
	})
	return file_pics_proto_rawDescData
}

var file_pics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pics_proto_goTypes = []interface{}{
	(*Pics)(nil),         // 0: protoc.Pics
	(*Pics_Picture)(nil), // 1: protoc.Pics.Picture
}
var file_pics_proto_depIdxs = []int32{
	1, // 0: protoc.Pics.pic:type_name -> protoc.Pics.Picture
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pics_proto_init() }
func file_pics_proto_init() {
	if File_pics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pics_Picture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pics_proto_goTypes,
		DependencyIndexes: file_pics_proto_depIdxs,
		MessageInfos:      file_pics_proto_msgTypes,
	}.Build()
	File_pics_proto = out.File
	file_pics_proto_rawDesc = nil
	file_pics_proto_goTypes = nil
	file_pics_proto_depIdxs = nil
}
