# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pics.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\npics.proto\"]\n\x04Pics\x12\x1a\n\x03pic\x18\x01 \x03(\x0b\x32\r.Pics.Picture\x1a\x39\n\x07Picture\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x10\n\x08pic_data\x18\x03 \x01(\x0c\x62\x06proto3'
)




_PICS_PICTURE = _descriptor.Descriptor(
  name='Picture',
  full_name='Pics.Picture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Pics.Picture.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='Pics.Picture.location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pic_data', full_name='Pics.Picture.pic_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=107,
)

_PICS = _descriptor.Descriptor(
  name='Pics',
  full_name='Pics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pic', full_name='Pics.pic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PICS_PICTURE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=107,
)

_PICS_PICTURE.containing_type = _PICS
_PICS.fields_by_name['pic'].message_type = _PICS_PICTURE
DESCRIPTOR.message_types_by_name['Pics'] = _PICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pics = _reflection.GeneratedProtocolMessageType('Pics', (_message.Message,), {

  'Picture' : _reflection.GeneratedProtocolMessageType('Picture', (_message.Message,), {
    'DESCRIPTOR' : _PICS_PICTURE,
    '__module__' : 'pics_pb2'
    # @@protoc_insertion_point(class_scope:Pics.Picture)
    })
  ,
  'DESCRIPTOR' : _PICS,
  '__module__' : 'pics_pb2'
  # @@protoc_insertion_point(class_scope:Pics)
  })
_sym_db.RegisterMessage(Pics)
_sym_db.RegisterMessage(Pics.Picture)


# @@protoc_insertion_point(module_scope)
