[server]
mode = "debug"
port = 8081
read_timeout = 60
write_timeout = 60

[mysql]
user = "root"
<<<<<<< HEAD
passwd = "114514"
=======
passwd = "xxxxx"
>>>>>>> a419de720b20bbb1b6c734ecd3ef0c2246acbcc8
host = "localhost"
port = 3306
name = "traffic"